### ISSUE TITLE
Establish communication with PR officers of other orgs

### ISSUE THREAD

**Issue by wheitman** [Nova-UTD/navigator#110]

**Comment by wheitman** [comment]
@Vion868 any updates on this?

**Comment by Vion868** [comment]
Actually happening later today! One of IEEE's Officers is a part of SWE and our Officer Meeting is later tonight. I'm asking them about it then. In terms of ACM, that will be this weekend, I was planning on talking with them earlier this week but our plans changed last minute

**Comment by wheitman** [comment]
All done: https://nova-utd.github.io/deep/dives/2021/11/12/Data-Visualization-&-Interface.html
