### ISSUE TITLE
Add kinematic data to model and port to SVL

### ISSUE THREAD

**Issue by wheitman** [Nova-UTD/navigator#118]

**Comment by joshmackwilliams** [comment]
Issues should stay in the "New Issues" pipeline until they've been estimated (and don't just do this yourself - multiple members are supposed to estimate every task)

**Comment by joshmackwilliams** [comment]
Tech art issues don't actually necessarily need estimates, and voting isn't particularly meaningful since we only have one artist. Feel free to add an estimate, but it's not required. I'm moving this one back to backlog.
