### ISSUE TITLE
Set up visual demo using 3D model

### ISSUE THREAD

**Issue by wheitman** [Nova-UTD/navigator#119]
Ex: https://sketchfab.com/3d-models/pagani-huayra-bc-metallic-beryllium-orange-f3a4774883284e748b9081d2b2c60ed5

**Comment by joshmackwilliams** [comment]
Issues should stay in the "New Issues" pipeline until they've been estimated (and don't just do this yourself - multiple members are supposed to estimate every task)

**Comment by joshmackwilliams** [comment]
Tech art issues don't actually necessarily need estimates, and voting isn't particularly meaningful since we only have one artist. Feel free to add an estimate, but it's not required. I'm moving this one back to backlog.

**Comment by wheitman** [comment]
@G-Salmon would you please add a link to that demo of the race car that you referenced in our meeting?

**Comment by G-Salmon** [comment]
added
