### ISSUE TITLE
Create 3D model of ZED cameras

### ISSUE THREAD

**Issue by wheitman** [Nova-UTD/navigator#120]
![1.png](https://images.zenhubusercontent.com/617cad4fd06216d5dd7f353b/b7651971-5a21-4dc8-8b11-486779a7b4b1)

**Comment by wheitman** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nova-ZenHub-61760061bdbc0e001eae726d/issues/Nova-UTD/navigator/120?planning-poker) with ZenHub @G-Salmon

**Comment by wheitman** [comment]
@G-Salmon is this complete? If so, would you post a link to the model or a rendering here for our records?

**Comment by G-Salmon** [comment]
Oh I was gonna post the stuff in General for tomorrow meeting, I'll post it here after the meeting _cause I won't have much to show otherwise_

**Comment by G-Salmon** [comment]
![3.png](https://images.zenhubusercontent.com/617cad4fd06216d5dd7f353b/619c9530-0eff-423c-af33-eed4ce794f95)
