### ISSUE TITLE
Create node.js shell

### ISSUE THREAD

**Issue by wheitman** [Nova-UTD/navigator#128]

**Comment by wheitman** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nova-ZenHub-61760061bdbc0e001eae726d/issues/Nova-UTD/navigator/128?planning-poker) with ZenHub @zzeneric

**Comment by wheitman** [comment]
@zzeneric if you link a PR to this, that will allow @joshmackwilliams and I to review and close this.

**Comment by zzeneric** [comment]
Done: reopening older PR with the new updates

**Comment by wheitman** [comment]
Stale. Closed.
