### ISSUE TITLE
Implement rclnodejs library

### ISSUE THREAD

**Issue by wheitman** [Nova-UTD/navigator#129]

**Comment by wheitman** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nova-ZenHub-61760061bdbc0e001eae726d/issues/Nova-UTD/navigator/129?planning-poker) with ZenHub @zzeneric

**Comment by zzeneric** [comment]
New PR will not be using rclnodejs as discussed, but the replacement will be on the reopened older PR with the new updates
