### ISSUE TITLE
Receive and submit ROS messages

### ISSUE THREAD

**Issue by wheitman** [Nova-UTD/navigator#131]

**Comment by wheitman** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nova-ZenHub-61760061bdbc0e001eae726d/issues/Nova-UTD/navigator/131?planning-poker) with ZenHub @zzeneric

**Comment by zzeneric** [comment]
Done: reopening older PR with the new updates
(This is only tested currently with rclcpp pub command, have not implemented into any other nodes currently)
