### ISSUE TITLE
Create client interpretation module

### ISSUE THREAD

**Issue by wheitman** [Nova-UTD/navigator#133]

**Comment by wheitman** [comment]
@zzeneric could you please clarify this Issue?

**Comment by wheitman** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nova-ZenHub-61760061bdbc0e001eae726d/issues/Nova-UTD/navigator/133?planning-poker) with ZenHub @zzeneric

**Comment by zzeneric** [comment]
Done: reopening older PR with the new updates
