### ISSUE TITLE
Update Navigator readme

### ISSUE THREAD

**Issue by wheitman** [Nova-UTD/navigator#144]

**Comment by wheitman** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nova-ZenHub-61760061bdbc0e001eae726d/issues/Nova-UTD/navigator/144?planning-poker) with ZenHub @joshmackwilliams

**Comment by joshmackwilliams** [comment]
This should not have been closed, but instead should have moved to "Done". Accorndingly, I'm reopening and moving it there
