### ISSUE TITLE
Create a basic safety manager

### ISSUE THREAD

**Issue by joshmackwilliams** [Nova-UTD/navigator#152]
## Problem
We need to integrate most of our nodes with the safety manager. However, there is currently no concrete interface with which they can integrate, making development difficult. 

## Solution
We need a basic safety manager that will allow nodes to be tested. This will potentially involve development of a library for reliable communication with the safety manager. 

## Success condition
We have a safety manager that receives and logs events reliably and can reliably send commands back.

**Comment by joshmackwilliams** [comment]
We can use a service (http://docs.ros.org/en/foxy/Tutorials/Services/Understanding-ROS2-Services.html) for reliable communication. Even if all we're sending back is an "ok" message, this model will guarantee that the desired target receives the message. For visualization and logging purposes, we can simply re-broadcast safety events from the safety manager itself. Alternatively, there may be a way to intercept and listen in on these calls - this will involve looking into how services are implemented. Each node also needs to run a service to receive commands from the safety manager as well.

**Comment by joshmackwilliams** [comment]
Progress update: voltron_test_utils now has a TestServer and a TestClient, so I can now start developing the actual safety manager itself.

**Comment by wheitman** [comment]
@joshmackwilliams any updates?

**Comment by joshmackwilliams** [comment]
All that remains on this issue is to create a basic safety manager that logs messages when safety events are raised (I'm planning to leave the actual logic to another issue, which I will open shortly). This should only take a couple hours, but I'm pretty swamped with assignments and an upcoming exam atm. You can expect this to be done by next meeting for sure.

**Comment by joshmackwilliams** [comment]
Also, turns out we will not need a special library (just use ROS servers and clients). I've put the srv files in voltron_msgs

**Comment by joshmackwilliams** [comment]
Updated the technical doc to reflect what's currently been done as far as implementing the service interfaces

**Comment by joshmackwilliams** [comment]
This has been reviewed and merged, so I'm closing it now
