### ISSUE TITLE
Update lab digital signage

### ISSUE THREAD

**Issue by wheitman** [Nova-UTD/navigator#161]
This can be a PowerPoint presentation, a slideshow screensaver, a custom website, or something else. Should include small team updates, at least one member highlight, and a website callout. Optionally includes project facts, team pictures, a project countdown timer, etc. We can keep it simple at the start and add content later on.

**Comment by wheitman** [comment]
@Vion868 where do we stand here?

**Comment by Vion868** [comment]
@wheitman Take a look at them, adding lots of photos of the car and going to add more of our weekly meetings! I have plenty more to add now that I have a good backlog of content

**Comment by Vion868** [comment]
Need to add more transitions and I'd like to add more word slides, but I think that this is something that won't truly ever be done. I'm going to add more to it and change it all the time!

**Comment by wheitman** [comment]
Looks great! I just made one minor edit to slide 2. Looking forward to seeing these slides evolve.

**Comment by Vion868** [comment]
I'm planning now on adding interesting pics from each of our weekly meetings on there each week now (specifically if they look interesting...I.E. the more whiteboard drawings people do, the better!). My current backlog of photos means I can start rotating photos in and out at present without needing new ones, but I'll always be collecting more

**Comment by wheitman** [comment]
I'll close this as soon as the timing on the slides is addressed @Vion868

**Comment by Vion868** [comment]
@wheitman Issues with timing are done, they should all play automatically and on a loop! I will be adding more photos to these slides as long as we keep going of course, but for now, this issue is "done"
