### ISSUE TITLE
Transform map and localization information into a usable format

### ISSUE THREAD

**Issue by wheitman** [Nova-UTD/navigator#17]

**Comment by wheitman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nova-ZenHub-61760061bdbc0e001eae726d/issues/Nova-UTD/navigator/17?planning-poker) with ZenHub @crsz20 @EganJ @jim-works @NikhilNarvekar123

**Comment by wheitman** [comment]
@jim-works would you mind adding some details about this in the Issue description?

**Comment by jim-works** [comment]
Take in the lanelet map data and convert each lane and road boundary into a smaller length sequence of points such that creating the cubic spline through those points is a good estimate of the boundaries. I can fill in more details of the implementation once I look at the code.

**Comment by wheitman** [comment]
@jim-works what's the progress on this? Could you use some extra help?

**Comment by jim-works** [comment]
> @jim-works what's the progress on this? Could you use some extra help?

Nope, this is done except for unit tests. Turns out auto ware had a decent amount of code for this, which I copied and modified.

**Comment by wheitman** [comment]
@jim-works Have these unit tests been written?

> > @jim-works what's the progress on this? Could you use some extra help?
> 
> Nope, this is done except for unit tests. Turns out auto ware had a decent amount of code for this, which I copied and modified.

Have these unit tests been written? @jim-works

**Comment by joshmackwilliams** [comment]
Published in v1.1.0
