### ISSUE TITLE
Generate splines for map data

### ISSUE THREAD

**Issue by wheitman** [Nova-UTD/navigator#18]

**Comment by wheitman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nova-ZenHub-61760061bdbc0e001eae726d/issues/Nova-UTD/navigator/18?planning-poker) with ZenHub @crsz20 @EganJ @jim-works @NikhilNarvekar123

**Comment by wheitman** [comment]
@jim-works would you mind adding some details about this in the Issue description?

**Comment by jim-works** [comment]
Using the transformed map data, create cubic splines for each of the lane boundaries and road boundaries. This will be used in the cost function calculation later in the path planning.

**Comment by joshmackwilliams** [comment]
Published in v1.1.0
