### ISSUE TITLE
Republish ZED & SVL bounding boxes in abstract format

### ISSUE THREAD

**Issue by wheitman** [Nova-UTD/navigator#188]
### Problem
ZED and SVL use different formats for their object detection results. This means that our Navigator code can't be "blind" to whether it's being run on the car or in the simulator.

### Solution
Write a ROS node (preferably in C++) that subscribes to both the ZED and SVL results topics. The node then republishes the results in an abstact, platform-blind format. For example, car detections could be published to `/obstacles/cars` and so on.

### Success condition
When either a ZED [ObjectsStamped](https://github.com/stereolabs/zed-ros2-wrapper/blob/master/zed_interfaces/msg/ObjectsStamped.msg) or SVL [Detection3DArray](https://github.com/lgsvl/lgsvl_msgs/blob/master/msg/Detection3DArray.msg) message is received, the node republishes all objects in a custom, abstact message format.

The message format should be stored in the voltron_msgs package, and the output should be similar to ZED's [Object](https://github.com/stereolabs/zed-ros2-wrapper/blob/master/zed_interfaces/msg/Object.msg) msg, something like
        - object label (e.g. "car")
        - object identifier
        - float confidence ([0.01, 0.01, 0.99])
        - float width, height, length
        - [PoseStamped](https://docs.ros2.org/foxy/api/geometry_msgs/msg/PoseWithCovarianceStamped.html) pose
        - [Vector3Stamped](https://docs.ros2.org/foxy/api/geometry_msgs/msg/Vector3Stamped.html) velocity
        - int8 tracking_state
    
Note that ROS's [geometry_msgs](https://docs.ros2.org/foxy/api/geometry_msgs/index-msg.html) are used wherever possible.

**Comment by wheitman** [comment]
@rae0924 I've added the basics here. Please adjust as you see fit.

**Comment by ScallyK** [comment]
@rae0924 do you need me on this as well

**Comment by rae0924** [comment]
@ScallyK yeah, sorry for the late response, I will just need help with questions about the simulations. I can do the programming.

**Comment by wheitman** [comment]
Complete. Closed.
