### ISSUE TITLE
Set up ZED SDK on the Quad

### ISSUE THREAD

**Issue by wheitman** [Nova-UTD/navigator#189]
## Problem
While the ZED SDK is installed at `/usr/local/zed`, some users cannot access the files there. For example, tools like `/usr/loca/zed/tools/ZED_Explorer` don't appear to exist or have permission errors.

Building ROS packages that include ZED as a dependency fails. CMake appears not to be able to find the ZED SDK. This only seems to happen for users other than @wheitman, who installed the SDK in the first place.

## Solution
Not sure!

## Success conditions
- ROS packages that depend on the ZED SDK can be successfully built by all users
- All users can access and execute the tools found in `/usr/local/zed/tools`.

**Comment by wheitman** [comment]
@ScallyK what's the progress here?

**Comment by ScallyK** [comment]
working on it now, sorry for the late response

**Comment by ScallyK** [comment]
@wheitman this will need to be tested. otherwise I have another approach in mind

**Comment by wheitman** [comment]
@ScallyK have you tried making a dummy account and building the zed-ros2-wrapper? That should be a sufficient test.

What's your other approach?

**Comment by ScallyK** [comment]
yes, building the zed-ros2-wrapper works with my test account. please review
