### ISSUE TITLE
Write or revise minimal steering controller for Checkpoint C

### ISSUE THREAD

**Issue by wheitman** [Nova-UTD/navigator#211]
## Problem
Our current steering controller (`vt_steering_controller`) has not been updated since Demo 1 this summer. It will need to be adjusted to fit the new Path Planner (#209), or rewritten entirely.

## Solution
Adjust or rewrite our steering controller for Checkpoint C.

The input will be an ordered list of x-y coordinates representing our path (from the Path Planner). The output should be a steering effort, from -100% to +100%, representing the actual force to be applied to the steering wheel by our EPAS system.

Note that the output should no longer be a desired steering angle, but a steering effort instead.

## Success condition
The car steers smoothly both (A) in simulation and (B) in the real world.

## Notes
Instead of waiting for the Path Planner to be revised, we can manually compile a list of x-y coordinates for testing in simulation. See [here](https://ibb.co/0mz3PWq) for an example path in SVL's GoMentum Station map. Choose a sequence of points on this sample path and format them as a message, then publish this message to test the controller, without the need of a path planner.

**Comment by crsz20** [comment]
The node successfully receives Trajectory messages. Before testing in simulation, we must select & update the lookahead point & the closest point.
