### ISSUE TITLE
Create initial diagram of all accepting states and transition functions

### ISSUE THREAD

**Issue by wheitman** [Nova-UTD/navigator#29]

**Comment by NikhilNarvekar123** [comment]
This relates to BPC issue #7 . It involves creating the entire state diagram for all possible behaviors of the vehicle. Input data is perception information and output data is a chosen path, but this is subject to change based on what we determine in #7 .

**Comment by wheitman** [comment]
See https://github.com/Nova-UTD/navigator/wiki/Behavior-Planner-Overview

Great job
