### ISSUE TITLE
Publish OccupancyGrid for t=0

### ISSUE THREAD

**Issue by wheitman** [Nova-UTD/navigator#307]
- [x] Refactor existing code and test for reasonable result in `base_link`
- [x] Transform result to `map` frame

**Comment by danielv012** [comment]
Still needs refactoring, code is not at peak efficiency. However, in its current state, it's ready for use.

**Comment by wheitman** [comment]
Great job sticking with this. Can you make a PR so we can pull it into dev?

**Comment by danielv012** [comment]
Yep, was just about to do so.
