### ISSUE TITLE
Shadow cast the static occupancy grid

### ISSUE THREAD

**Issue by ashwin-som** [Nova-UTD/navigator#317]
## Problem
Currently, the occupancy grid does not have the unknown spaces accounted for, and are currently marked as available.

## Solution
I need to create a shadow casting algorithm for the occupancy grid. 

## Success condition
Unknown spots in the grid are accounted for (marked as 'unknown')

**Comment by wheitman** [comment]
Is this still necessary? @danielv012  @jesse51002

**Comment by ashwin-som** [comment]
I believe so, Daniel and I discussed this part would be be necessary after creating the static grid.
