### ISSUE TITLE
Find suitable 3D pedestrian/vehicle classification model

### ISSUE THREAD

**Issue by wheitman** [Nova-UTD/navigator#47]

**Comment by wheitman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nova-ZenHub-61760061bdbc0e001eae726d/issues/Nova-UTD/navigator/47?planning-poker) with ZenHub @DragonflyRobotics @JamesMonCode @rae0924

**Comment by wheitman** [comment]
@Nova-UTD/perception please assign one of yourselves to this and be ready to deliver a full report, including comparisons and a decision, by the end of our Sprint, Friday, Nov 19.

**Comment by rae0924** [comment]
report is [here](https://docs.google.com/document/d/1yAa_-0aoRVBYlJI38lPjPpsXyBmiR66-2avwAeXBpDE/edit?usp=sharing)
