### ISSUE TITLE
Provide each Quad user with a virtual network

### ISSUE THREAD

**Issue by wheitman** [Nova-UTD/navigator#64]
This network will be used for testing ROS packages, e.g. Navigator. This can be accomplished by:
- Giving each user a VM,
- Fixing Docker on the Quad
- Something else

The goal should be simplicity and minimal change to the actual Navigator codebase.

**Comment by wheitman** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nova-ZenHub-61760061bdbc0e001eae726d/issues/Nova-UTD/navigator/64?planning-poker) with ZenHub @ScallyK

**Comment by wheitman** [comment]
@ScallyK I've updated this Issue's details. Please adjust as you see fit.

**Comment by ScallyK** [comment]
attempted changing DDS platform. results pending
