### ISSUE TITLE
Clean-up old steering node and harvest useful pieces

### ISSUE THREAD

**Issue by wheitman** [Nova-UTD/navigator#88]

**Comment by wheitman** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nova-ZenHub-61760061bdbc0e001eae726d/issues/Nova-UTD/navigator/88?planning-poker) with ZenHub @a-bainbridge

**Comment by a-bainbridge** [comment]
It seems as though we'll need to completely replace the old steering node, as the design and needs of `tbs` are quite different. Therefore, the "clean-up" is simply to delete this node when the replacement is ready.
