### ISSUE TITLE
Write GPS node

### ISSUE THREAD

**Issue by wheitman** [Nova-UTD/navigator#94]

**Comment by wheitman** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nova-ZenHub-61760061bdbc0e001eae726d/issues/Nova-UTD/navigator/94?planning-poker) with ZenHub @a-bainbridge

**Comment by wheitman** [comment]
@a-bainbridge is this ready for review?

**Comment by a-bainbridge** [comment]
@wheitman I want to clean up a few things today before I submit for review.

**Comment by wheitman** [comment]
PR #159 done. Closed.
